spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: git@github.com:tianyaruobilin/itoken-config.git
          search-paths: repo
          username: 13657097058@163.com
          password: lrmqq1998

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://server1:8761/eureka/