server:
  port: 9090
spring:
  application:
    name: vts_sc_sharding_mybatis
  shardingsphere:
    datasource:
      names: ds0,ds1
  datasource:
    ds0:
      type: org.apache.commons.dbcp2.BasicDataSource
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://localhost:1433;database=user_0
      username: admin
      password: admin
mybatis:
  type-aliases-package: com.study.rwseparation.rwseparation.entity
  mapper-locations: classpath:mapper/*.xml
